import { Producto } from "../interfaces/tracking";

  export const productos: Producto[] = [
    {
      codigo: 12651,
      descripcion: "MONSTER ENERGY KHAOS (NARANJA) LATA 24 U",
      sku: 2554,
      precioVenta: 562.44,
      costo: 54,
      margen: 85,
      existencia: 90,
      stockMinimo: -98,
      stockMaximo: 90,
      marca: "MONSTER",
      idMarca: 2554,
      categoria: "NAB'S",
      subcategoria: "ENERGIZANTE",
      presentacion: "16 onz.",
      envase: "Lata",
      peso: 0.113562,
      unidadMedida: "70",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13908,
      descripcion: "SALVA VIDA 12OZ LAT 24U",
      sku: 1009,
      precioVenta: 93.21,
      costo: 54,
      margen: 85,
      existencia: -18,
      stockMinimo: 136,
      stockMaximo: -81,
      marca: "SALVA VIDA",
      idMarca: 1009,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "12 onz.",
      envase: "Lata",
      peso: 0.085172,
      unidadMedida: "108",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13909,
      descripcion: "PORT ROYAL 12OZ LAT 24U",
      sku: 1022,
      precioVenta: 97.71,
      costo: 54,
      margen: 85,
      existencia: -18,
      stockMinimo: 82,
      stockMaximo: -81,
      marca: "PORT ROYAL",
      idMarca: 1022,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "12 onz.",
      envase: "Lata",
      peso: 0.085172,
      unidadMedida: "99",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13910,
      descripcion: "BARENA 12 OZ LAT 24U",
      sku: 1028,
      precioVenta: 91.74,
      costo: 30,
      margen: 47,
      existencia: 50,
      stockMinimo: -26,
      stockMaximo: 50,
      marca: "BARENA",
      idMarca: 1028,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "12 onz.",
      envase: "Lata",
      peso: 0.085172,
      unidadMedida: "108",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13911,
      descripcion: "IMPERIAL 12OZ LAT 24U",
      sku: 1042,
      precioVenta: 93.93,
      costo: 45,
      margen: 71,
      existencia: -33,
      stockMinimo: 136,
      stockMaximo: -96,
      marca: "IMPERIAL",
      idMarca: 1042,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "12 onz.",
      envase: "Lata",
      peso: 0.085172,
      unidadMedida: "108",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13912,
      descripcion: "SALVA VIDA 12OZ VR 24U",
      sku: 1064,
      precioVenta: 36.53,
      costo: 48,
      margen: 76,
      existencia: -28,
      stockMinimo: 142,
      stockMaximo: -91,
      marca: "SALVA VIDA",
      idMarca: 1064,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "12 onz. Vidrio",
      envase: "Vidrio",
      peso: 0.085172,
      unidadMedida: "49",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13913,
      descripcion: "IMPERIAL 12OZ VR 24U",
      sku: 1065,
      precioVenta: 38.04,
      costo: 30,
      margen: 47,
      existencia: 50,
      stockMinimo: -104,
      stockMaximo: 50,
      marca: "IMPERIAL",
      idMarca: 1065,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "12 onz. Vidrio",
      envase: "Vidrio",
      peso: 0.085172,
      unidadMedida: "49",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13915,
      descripcion: "IMPERIAL 25OZ VR 12U",
      sku: 1069,
      precioVenta: 38.85,
      costo: 45,
      margen: 71,
      existencia: 82,
      stockMinimo: -96,
      stockMaximo: -33,
      marca: "IMPERIAL",
      idMarca: 1069,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "25 onz. Vidrio",
      envase: "Vidrio",
      peso: 0.09,
      unidadMedida: "36",
      factorConversion: 12,
      unidadesPorCaja: 12,
    },
    {
      codigo: 13916,
      descripcion: "PORT ROYAL 12OZ VR 24U",
      sku: 1074,
      precioVenta: 39.42,
      costo: 48,
      margen: 76,
      existencia: -136,
      stockMinimo: 322,
      stockMaximo: -262,
      marca: "PORT ROYAL",
      idMarca: 1074,
      categoria: "NAB'S",
      subcategoria: "REFRESCO",
      presentacion: "12 onz. Vidrio",
      envase: "Vidrio",
      peso: 0.085172,
      unidadMedida: "49",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13917,
      descripcion: "BARENA 12OZ VR 24U",
      sku: 1076,
      precioVenta: 36.83,
      costo: 54,
      margen: 85,
      existencia: 90,
      stockMinimo: 10,
      stockMaximo: 90,
      marca: "BARENA",
      idMarca: 1076,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "12 onz. Vidrio",
      envase: "Vidrio",
      peso: 0.085172,
      unidadMedida: "49",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13918,
      descripcion: "SALVA VIDA 12OZ LAT 12U",
      sku: 1082,
      precioVenta: 48.3,
      costo: 36,
      margen: 57,
      existencia: -48,
      stockMinimo: 64,
      stockMaximo: -111,
      marca: "SALVA VIDA",
      idMarca: 1082,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "12 onz. Lata",
      envase: "Lata",
      peso: 0.042586,
      unidadMedida: "216",
      factorConversion: 12,
      unidadesPorCaja: 12,
    },
    {
      codigo: 13919,
      descripcion: "SALVA VIDA 25OZ VR 12U",
      sku: 1096,
      precioVenta: 37.12,
      costo: 48,
      margen: 76,
      existencia: -82,
      stockMinimo: 244,
      stockMaximo: -176,
      marca: "SALVA VIDA",
      idMarca: 1096,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "25 onz. Vidrio",
      envase: "Vidrio",
      peso: 0.09,
      unidadMedida: "36",
      factorConversion: 12,
      unidadesPorCaja: 12,
    },
    {
      codigo: 13921,
      descripcion: "PORT ROYAL 21 OZ VR 12U",
      sku: 1122,
      precioVenta: 35.5,
      costo: 48,
      margen: 76,
      existencia: -139,
      stockMinimo: 321,
      stockMaximo: -266,
      marca: "PORT ROYAL",
      idMarca: 1122,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "21 onz. Vidrio",
      envase: "Vidrio",
      peso: 0.075,
      unidadMedida: "36",
      factorConversion: 12,
      unidadesPorCaja: 12,
    },
    {
      codigo: 13925,
      descripcion: "SALVA VIDA 16OZ LAT 24U",
      sku: 1154,
      precioVenta: 123.98,
      costo: 108,
      margen: 171,
      existencia: 72,
      stockMinimo: 145,
      stockMaximo: 9,
      marca: "SALVA VIDA",
      idMarca: 1154,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "16 onz. Lata",
      envase: "Lata",
      peso: 0.113562,
      unidadMedida: "72",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13927,
      descripcion: "IMPERIAL 16OZ LAT 24U",
      sku: 1156,
      precioVenta: 124.65,
      costo: 54,
      margen: 85,
      existencia: 90,
      stockMinimo: 10,
      stockMaximo: 90,
      marca: "IMPERIAL",
      idMarca: 1156,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "16 onz. Lata",
      envase: "Lata",
      peso: 0.113562,
      unidadMedida: "72",
      factorConversion: 24,
      unidadesPorCaja: 24,
    },
    {
      codigo: 13928,
      descripcion: "BARENA 12OZ LAT 12U",
      sku: 1165,
      precioVenta: 46.06,
      costo: 0,
      margen: 0,
      existencia: 0,
      stockMinimo: -98,
      stockMaximo: 0,
      marca: "BARENA",
      idMarca: 1165,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "12 onz. Lata",
      envase: "Lata",
      peso: 0.042586,
      unidadMedida: "216",
      factorConversion: 12,
      unidadesPorCaja: 12,
    },
    {
      codigo: 13930,
      descripcion: "BARENA 25OZ VR 12U",
      sku: 1168,
      precioVenta: 36.97,
      costo: 54,
      margen: 85,
      existencia: 90,
      stockMinimo: 10,
      stockMaximo: 90,
      marca: "BARENA",
      idMarca: 1168,
      categoria: "CERVEZA",
      subcategoria: "CERVEZA",
      presentacion: "25 onz. Vidrio",
      envase: "Vidrio",
      peso: 0.09,
      unidadMedida: "36",
      factorConversion: 24,
      unidadesPorCaja: 24,
    }
    ];